name: DEBUG

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        

jobs:
  example_job:
      runs-on: ubuntu-latest
      steps:
        - name: Get environment ID - qa hardcoded
          run: echo "Environment ID is ${{ environments.qa.id }}"
        
  debug:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
   
      - name: Dump environments
        env:
          ENVIRONMENTS: ${{ toJson(environments) }}
        run: echo "$ENVIRONMENTS"
        
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
        
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
