name: Deploy to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: gmud
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Print Environment
        run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          
      - name: de facto deploy
        run: |
          echo "de facto deploying..."
