name: needs

on:
  workflow_dispatch:

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Job A
        run: echo "This is job A"

  jobB:
    needs: jobA
    runs-on: ubuntu-latest
    steps:
      - name: Job B
        run: exit 1

  jobC:
    needs: [jobA, jobB]
    if: always()
    runs-on: ubuntu-latest
    steps:
    
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
        
      - name: Job C
        run: |
          if [ ${{ needs.jobB.result }} = 'failure' ]; then
            echo "Job B failed"
          else
            echo "Job B succeeded"
          fi
