name: PostgreSQL service example
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: postgres
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: echo
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: echo OKKKK
  
