name: Deploy to Environment

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      aprovador_gmud:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Print Environment
        run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "aprovador_gmud: ${{ github.event.inputs.aprovador_gmud }}" 

